#!/bin/bash
if [[ `uname -s` == "Darwin" ]]; then
    LIBSNARK_FLAGS="NO_PROCPS=1 NO_GTEST=1 NO_DOCS=1"
fi

set -x -e

if [ $# -ge 1 ]; then
  if [ $1 = "debug" ]; then
    echo "Setting debug flags"
    DEBUG=debug
    LIBSNARK_FLAGS="$LIBSNARK_FLAGS DEBUG=1"
  fi
fi

DEPSRC=./depsrc
DEPINST=./depinst

mkdir -p $DEPINST
DEPINST=`pwd -P`/$DEPINST  # remember absolute path

mkdir -p $DEPSRC
cd $DEPSRC

[ ! -d libsnark ] && git clone https://github.com/marmolejo/libsnark libsnark
cd libsnark
git pull
# TODO: submit -fPIC patch to ate-pairing
INC_DIR=-fPIC ./prepare-depends.sh $DEBUG
make clean
make $LIBSNARK_FLAGS
make install PREFIX=$DEPINST $LIBSNARK_FLAGS
cd ..

cd ..
